# Schema for the configuration files of the PuPa Theme theme.
publicpalika.settings:
  type: theme_settings
  label: 'PuPa Theme settings'
  mapping:
    example:
      type: string
      label: Example
